# Generated by Django 4.2 on 2023-04-08 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='shoes',
        ),
    ]
