# Generated by Django 4.2 on 2023-04-08 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
        ('rating', '0003_remove_rating_shoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='shoes_avaliated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shoes.shoes'),
        ),
    ]
