# Generated by Django 4.2 on 2023-06-03 19:43

from django.db import migrations, models
import shoes.models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=shoes.models.get_image_filename),
        ),
        migrations.AddField(
            model_name='shoes',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
