# Generated by Django 4.2 on 2023-04-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoes_name', models.CharField(default='Generico', max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
    ]
