# Generated by Django 4.2 on 2023-04-08 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_rating_shoes_avaliated'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='grade',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
